# Generated by Django 3.0.8 on 2022-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasemodel',
            name='disease_img',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
