# Generated by Django 3.0.8 on 2022-10-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfsapp', '0002_auto_20221024_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasemodel',
            old_name='disease_img',
            new_name='diseaseimg',
        ),
    ]
